CREATE TABLE Person (
  Id INTEGER IDENTITY(1,1),
  FirstName VARCHAR(40) NOT NULL,
  LastName VARCHAR(60) NOT NULL,
  DOB DATE NOT NULL,
  CreateDate DATE NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Book (
  Id INTEGER IDENTITY(1,1),
  Title VARCHAR(40) NOT NULL,
  Author VARCHAR(100) NOT NULL,
  AddDate DATE NULL,
  IsLost BOOLEAN DEFAULT(FALSE) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Borrow (
  Id INTEGER IDENTITY(1,1),
  PersonId INTEGER NOT NULL,
  BookId INTEGER NOT NULL,
  RentalDate DATE NOT NULL,
  DeliveryDate DATE NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (PersonId) REFERENCES Person(Id),
  FOREIGN KEY (BookId) REFERENCES Book(Id)
);